// examples/react/src/App.jsx
import React, { Component } from 'react';
import { Page, Form, Rating, Stepper, Switch } from 'mobiscroll-react';
import 'mobiscroll-react/dist/css/mobiscroll.min.css';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <Page>
        <div className="App">
          <header className="App-header">
            <img src={logo} className="App-logo" alt="logo" />
            <h1 className="App-title">Welcome to React</h1>
          </header>
        </div>
        <Form>
          <div className="mbsc-form-group">
            <div className="mbsc-form-group-title">Account information</div>
            <label>
              First Name
              <input type="text" placeholder="What's your first name?" />
            </label>
            <label>
              Last Name
              <input type="text" placeholder="What's your last name?" />
            </label>
            <label>
              Email
              <input type="email" placeholder="me@domain.com" />
            </label>
            <label>
              Password
              <input type="password" placeholder="Minimum 6 characters" data-password-toggle="true" />
            </label>
            <Rating value={4}>
              Rating
            </Rating>
          </div>
          <div className="mbsc-form-group">
            <div className="mbsc-form-group-title">About you</div>
            <label>
              Male
              <input type="radio" data-role="segmented" name="gender" defaultChecked />
            </label>
            <label>
              Female
              <input type="radio" data-role="segmented" name="gender" />
            </label>
            <Stepper min={130} max={220} value={170} data-val="left">
              Height (cm)
            </Stepper>
            <Stepper min={30} max={180} value={85} data-val="left">
              Weight (kg)
            </Stepper>
          </div>

          <div className="mbsc-form-group">
            <div className="mbsc-form-group-title">General settings</div>
            <Switch>
              Indoor/Treadmill
            </Switch>
            <Switch defaultChecked>
              Auto-Pause Run
              <span className="mbsc-desc">
                Automatically pause workout when you stop moving. This is useful if you don&apos;t want to manually pause and resume.
              </span>
            </Switch>
          </div>

          <div className="mbsc-form-group">
            <div className="mbsc-form-group-title">On screen</div>
            <Switch defaultChecked>
              Heart Rate
            </Switch>
            <Switch>
              Cheers
            </Switch>
            <label>
              Show current pace
              <input type="radio" data-role="segmented" name="pace" defaultChecked />
            </label>
            <label>
              Show average pace
              <input type="radio" data-role="segmented" name="pace" />
            </label>
          </div>

          <div className="mbsc-form-group">
            <div className="mbsc-form-group-title">Run countdown</div>
            <label>
              <input type="radio" name="group" /> Off
            </label>
            <label>
              <input type="radio" name="group" defaultChecked /> 3 seconds
            </label>
            <label>
              <input type="radio" name="group" /> 6 seconds
            </label>
            <label>
              <input type="radio" name="group" /> 9 seconds
            </label>
          </div>

          <div className="mbsc-btn-group-block">
            <button>Save Settings</button>
          </div>
        </Form>
      </Page>
    );
  }
}

export default App;

// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  rating: number = 4;
  gender: string = 'male';
  height: number = 170;
  weight: number = 85;
  indoor: boolean;
  cheers: boolean;
  pause: boolean = true;
  heartRate: boolean = true;
  pace: string = 'current';
  countdown: number = 3;
}

<mbsc-page>
    <mbsc-form>
        <div class="mbsc-form-group">
            <div class="mbsc-form-group-title">Account information</div>
            <mbsc-input [(ngModel)]="firstName" placeholder="What's your first name?">First Name</mbsc-input>
            <mbsc-input [(ngModel)]="lastName" placeholder="What's your last name?">Last Name</mbsc-input>
            <mbsc-input [(ngModel)]="email" placeholder="me@domain.com">Email</mbsc-input>
            <mbsc-input [(ngModel)]="password" placeholder="Minimum 6 characters" type="password" minlength="6" required [password-toggle]="true">Password</mbsc-input>
            <mbsc-rating [(ngModel)]="rating">Rating</mbsc-rating>
        </div>
        <div class="mbsc-form-group">
            <div class="mbsc-form-group-title">About you</div>
            <mbsc-segmented-group [(ngModel)]="gender">
                <mbsc-segmented value="male">Male</mbsc-segmented>
                <mbsc-segmented value="female">Female</mbsc-segmented>
            </mbsc-segmented-group>
            <mbsc-stepper [(ngModel)]="height" min="130" max="220" val="left">Height (cm)</mbsc-stepper>
            <mbsc-stepper [(ngModel)]="weight" min="30" max="180" val="left">Weight (kg)</mbsc-stepper>
        </div>
        <div class="mbsc-form-group">
            <div class="mbsc-form-group-title">General settings</div>
            <mbsc-switch [(ngModel)]="indoor">Indoor/Treadmill</mbsc-switch>
            <mbsc-switch [(ngModel)]="pause">Auto-Pause Run
                <span class="mbsc-desc">Automatically pause workout when you stop moving. This is useful if you don't want to manually pause and resume.</span>
            </mbsc-switch>
        </div>
        <div class="mbsc-form-group">
            <div class="mbsc-form-group-title">On screen</div>
            <mbsc-switch [(ngModel)]="heartRate">Heart Rate</mbsc-switch>
            <mbsc-switch [(ngModel)]="cheers">Cheers</mbsc-switch>
            <mbsc-segmented-group [(ngModel)]="pace">
                <mbsc-segmented value="current">Show current pace</mbsc-segmented>
                <mbsc-segmented value="average">Show average pace</mbsc-segmented>
            </mbsc-segmented-group>
        </div>
        <div class="mbsc-form-group">
            <div class="mbsc-form-group-title">Run countdown</div>

            <mbsc-radio-group [(ngModel)]="countdown">
                <mbsc-radio value="off">Off</mbsc-radio>
                <mbsc-radio value="3">3 seconds</mbsc-radio>
                <mbsc-radio value="6">6 seconds</mbsc-radio>
                <mbsc-radio value="9">9 seconds</mbsc-radio>
            </mbsc-radio-group>
        </div>

        <div class="mbsc-btn-group-block">
            <mbsc-button>Save Settings</mbsc-button>
        </div>
    </mbsc-form>
</mbsc-page>
