// examples/react/src/App.tsx
import React, { Component } from 'react';
import { Page, Form, FormGroup, FormGroupContent, FormGroupTitle, Rating, Stepper, Switch, Input } from '@mobiscroll/react-lite';
import './App.scss';

class App extends Component {
  render() {
    return (
      <Page>
        <Form>
          <FormGroup collapsible open>
            <FormGroupTitle>Account information</FormGroupTitle>
            <FormGroupContent>
              <Input type="text" placeholder="What's your first name?" labelStyle="floating">First Name</Input>
              <Input type="text" placeholder="What's your last name?" labelStyle="floating">Last Name</Input>
              <Input type="email" placeholder="me@domain.com" labelStyle="floating">Email</Input>
              <Input type="password" placeholder="Minimum 6 characters" labelStyle="floating" passwordToggle={true}>Password</Input>
              <Rating value={4}>
                Rating
            </Rating>
            </FormGroupContent>
          </FormGroup>

          <FormGroup collapsible>
            <FormGroupTitle>About you</FormGroupTitle>
            <FormGroupContent>
              <label>
                Male
              <input type="radio" data-role="segmented" name="gender" defaultChecked />
              </label>
              <label>
                Female
              <input type="radio" data-role="segmented" name="gender" />
              </label>
              <Stepper min={130} max={220} value={170} data-val="left">
                Height (cm)
            </Stepper>
              <Stepper min={30} max={180} value={85} data-val="left">
                Weight (kg)
            </Stepper>
            </FormGroupContent>
          </FormGroup>

          <FormGroup collapsible>
            <FormGroupTitle>General settings</FormGroupTitle>
            <FormGroupContent>
              <Switch>
                Indoor/Treadmill
            </Switch>
              <Switch defaultChecked>
                Auto-Pause Run
              <span className="mbsc-desc">
                  Automatically pause workout when you stop moving. This is useful if you don&apos;t want to manually pause and resume.
              </span>
              </Switch>
            </FormGroupContent>
          </FormGroup>

          <FormGroup collapsible>
            <FormGroupTitle>On screen</FormGroupTitle>
            <FormGroupContent>
              <Switch defaultChecked>
                Heart Rate
            </Switch>
              <Switch>
                Cheers
            </Switch>
              <label>
                Show current pace
              <input type="radio" data-role="segmented" name="pace" defaultChecked />
              </label>
              <label>
                Show average pace
              <input type="radio" data-role="segmented" name="pace" />
              </label>
            </FormGroupContent>
          </FormGroup>

          <FormGroup collapsible>
            <FormGroupTitle>Run countdown</FormGroupTitle>
            <FormGroupContent>
              <label>
                <input type="radio" name="group" /> Off
            </label>
              <label>
                <input type="radio" name="group" defaultChecked /> 3 seconds
            </label>
              <label>
                <input type="radio" name="group" /> 6 seconds
            </label>
              <label>
                <input type="radio" name="group" /> 9 seconds
            </label>
            </FormGroupContent>
          </FormGroup>

          <div className="mbsc-btn-group-block">
            <button>Save Settings</button>
          </div>
        </Form>
      </Page>
    );
  }
}

export default App;

// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    firstName: string;
    lastName: string;
    email: string;
    password: string;
    rating = 4;
    gender = 'male';
    height = 170;
    weight = 85;
    indoor: boolean;
    cheers: boolean;
    pause = true;
    heartRate = true;
    pace = 'current';
    countdown = 3;
}

<mbsc-page>
    <mbsc-form label-style="floating">
        <mbsc-form-group collapsible [open]="true">
            <mbsc-form-group-title>Account information</mbsc-form-group-title>
            <mbsc-form-group-content>
                <mbsc-input [(ngModel)]="firstName" placeholder="What's your first name?">First
                    Name</mbsc-input>
                <mbsc-input [(ngModel)]="lastName" placeholder="What's your last name?">Last Name
                </mbsc-input>
                <mbsc-input [(ngModel)]="email" placeholder="me@domain.com">
                    Email
                </mbsc-input>
                <mbsc-input [(ngModel)]="password" placeholder="Minimum 6 characters" type="password" [minlength]="6"
                    required [password-toggle]="true">
                    Password</mbsc-input>
                <mbsc-rating [(ngModel)]="rating">Rating</mbsc-rating>
            </mbsc-form-group-content>
        </mbsc-form-group>
        <mbsc-form-group collapsible>
            <mbsc-form-group-title>About you</mbsc-form-group-title>
            <mbsc-form-group-content>
                <mbsc-segmented-group [(ngModel)]="gender">
                    <mbsc-segmented value="male">Male</mbsc-segmented>
                    <mbsc-segmented value="female">Female</mbsc-segmented>
                </mbsc-segmented-group>
                <mbsc-stepper [(ngModel)]="height" [min]="130" [max]="220" val="left">Height (cm)</mbsc-stepper>
                <mbsc-stepper [(ngModel)]="weight" [min]="30" [max]="180" val="left">Weight (kg)</mbsc-stepper>
            </mbsc-form-group-content>
        </mbsc-form-group>
        <mbsc-form-group collapsible>
            <mbsc-form-group-title>General settings</mbsc-form-group-title>
            <mbsc-form-group-content>
                <mbsc-switch [(ngModel)]="indoor">Indoor/Treadmill</mbsc-switch>
                <mbsc-switch [(ngModel)]="pause">Auto-Pause Run
                    <span class="mbsc-desc">Automatically pause workout when you stop moving. This is useful if you
                        don't want to manually pause and resume.</span>
                </mbsc-switch>
            </mbsc-form-group-content>
        </mbsc-form-group>
        <mbsc-form-group collapsible>
            <mbsc-form-group-title>On screen</mbsc-form-group-title>
            <mbsc-form-group-content>
                <mbsc-switch [(ngModel)]="heartRate">Heart Rate</mbsc-switch>
                <mbsc-switch [(ngModel)]="cheers">Cheers</mbsc-switch>
                <mbsc-segmented-group [(ngModel)]="pace">
                    <mbsc-segmented value="current">Show current pace</mbsc-segmented>
                    <mbsc-segmented value="average">Show average pace</mbsc-segmented>
                </mbsc-segmented-group>
            </mbsc-form-group-content>
        </mbsc-form-group>
        <mbsc-form-group collapsible>
            <mbsc-form-group-title>Run countdown</mbsc-form-group-title>
            <mbsc-form-group-content>
                <mbsc-radio-group [(ngModel)]="countdown">
                    <mbsc-radio value="off">Off</mbsc-radio>
                    <mbsc-radio value="3">3 seconds</mbsc-radio>
                    <mbsc-radio value="6">6 seconds</mbsc-radio>
                    <mbsc-radio value="9">9 seconds</mbsc-radio>
                </mbsc-radio-group>
            </mbsc-form-group-content>
        </mbsc-form-group>

        <div class="mbsc-btn-group-block">
            <mbsc-button>Save Settings</mbsc-button>
        </div>
    </mbsc-form>
</mbsc-page>
